In [1]:
!pip install ucimlrepo


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
from ucimlrepo import fetch_ucirepo 
  
abalone = fetch_ucirepo(id=1) 

X = abalone.data.features 
y = abalone.data.targets 

print(abalone.metadata) 
print(abalone.variables) 

{'uci_id': 1, 'name': 'Abalone', 'repository_url': 'https://archive.ics.uci.edu/dataset/1/abalone', 'data_url': 'https://archive.ics.uci.edu/static/public/1/data.csv', 'abstract': 'Predict the age of abalone from physical measurements', 'area': 'Biology', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Tabular'], 'num_instances': 4177, 'num_features': 8, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': [], 'target_col': ['Rings'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1994, 'last_updated': 'Mon Aug 28 2023', 'dataset_doi': '10.24432/C55C7W', 'creators': ['Warwick Nash', 'Tracy Sellers', 'Simon Talbot', 'Andrew Cawthorn', 'Wes Ford'], 'intro_paper': None, 'additional_info': {'summary': 'Predicting the age of abalone from physical measurements.  The age of abalone is determined by cutting the shell through the cone, staining it, and counting the number of rings through a microscope -- 

In [13]:
import numpy as np
import pandas as pd

In [18]:
df=pd.concat([X,y],axis=1)

In [20]:
df.head(5)

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell_weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [21]:
print(f"the number of rows in the dataset : {len(df)}")

the number of rows in the dataset : 4177


In [22]:
print(f"colnames: {df.columns}")

colnames: Index(['Sex', 'Length', 'Diameter', 'Height', 'Whole_weight', 'Shucked_weight',
       'Viscera_weight', 'Shell_weight', 'Rings'],
      dtype='object')



1. input is :  'Sex', 'Length', 'Diameter', 'Height', 'Whole_weight', 'Shucked_weight','Viscera_weight', 'Shell_weight'
2. output is :  age of abalone
3. output is numeric because we are calculating the value of age and its a numeric term.

In [24]:
#converting the target(rings) to y(Age) where y=rings+1.5 
y=df['Rings']+1.5

In [25]:
df['Rings']

0       15
1        7
2        9
3       10
4        7
        ..
4172    11
4173    10
4174     9
4175    10
4176    12
Name: Rings, Length: 4177, dtype: int64

In [26]:
y

0       16.5
1        8.5
2       10.5
3       11.5
4        8.5
        ... 
4172    12.5
4173    11.5
4174    10.5
4175    11.5
4176    13.5
Name: Rings, Length: 4177, dtype: float64

In [28]:
# in order to train the model , we will choose these 3 input parameters -> length , diameter and whole weight of abalone.
df=df[['Length','Diameter','Whole_weight']]

In [96]:
df

Length  Diameter  Whole_weight  Rings
0      0.455     0.365        0.5140   16.5
1      0.350     0.265        0.2255    8.5
2      0.530     0.420        0.6770   10.5
3      0.440     0.365        0.5160   11.5
4      0.330     0.255        0.2050    8.5
...      ...       ...           ...    ...
4172   0.565     0.450        0.8870   12.5
4173   0.590     0.440        0.9660   11.5
4174   0.600     0.475        1.1760   10.5
4175   0.625     0.485        1.0945   11.5
4176   0.710     0.555        1.9485   13.5

[4177 rows x 4 columns]

In [33]:
df=pd.concat([df,y],axis=1)

In [34]:
df

Length  Diameter  Whole_weight  Rings
0      0.455     0.365        0.5140   16.5
1      0.350     0.265        0.2255    8.5
2      0.530     0.420        0.6770   10.5
3      0.440     0.365        0.5160   11.5
4      0.330     0.255        0.2050    8.5
...      ...       ...           ...    ...
4172   0.565     0.450        0.8870   12.5
4173   0.590     0.440        0.9660   11.5
4174   0.600     0.475        1.1760   10.5
4175   0.625     0.485        1.0945   11.5
4176   0.710     0.555        1.9485   13.5

[4177 rows x 4 columns]

this df is the final dataset we will be using to train the model.

In [97]:
X=df[['Length', 'Diameter', 'Whole_weight']].values 
y=df['Rings'].values   

In [98]:
X

array([[0.455 , 0.365 , 0.514 ],
       [0.35  , 0.265 , 0.2255],
       [0.53  , 0.42  , 0.677 ],
       ...,
       [0.6   , 0.475 , 1.176 ],
       [0.625 , 0.485 , 1.0945],
       [0.71  , 0.555 , 1.9485]], shape=(4177, 3))

In [99]:
y

array([16.5,  8.5, 10.5, ..., 10.5, 11.5, 13.5], shape=(4177,))

In [100]:
#train-test-split

import random

def traintestsplit(X,y,testsize=0.3,randomseed=None):
    data=list(zip(X,y))

    if randomseed is not None:
        random.seed(randomseed)
    
    random.shuffle(data)

    idx=int(len(data)*(1-testsize))
    train=data[:idx]
    test=data[idx:]

    X_train,y_train=zip(*train)
    X_test,y_test=zip(*test)

    return (np.array(X_train),np.array(X_test),np.array(y_train),np.array(y_test) )   



In [101]:
X_train,X_test,y_train,y_test=traintestsplit(X,y,testsize=0.2,randomseed=42)

In [103]:
print(X_train.shape)
print(y_train.shape)

print()

print(X_test.shape)
print(y_test.shape)

(3341, 3)
(3341,)

(836, 3)
(836,)


In [104]:
print(X_train)

[[0.62   0.5    1.3915]
 [0.4    0.3    0.318 ]
 [0.375  0.28   0.2565]
 ...
 [0.55   0.42   0.816 ]
 [0.495  0.395  0.5415]
 [0.64   0.505  1.3185]]


In [105]:
y_train=y_train.reshape(-1,1)
y_test=y_test.reshape(-1,1)

In [106]:
print(X_train.shape)
print(y_train.shape)

print()

print(X_test.shape)
print(y_test.shape)

(3341, 3)
(3341, 1)

(836, 3)
(836, 1)


In [107]:
class StandardScaler:
  def __init__(self):
    self.mean=None
    self.std=None

  def fit(self,X):
    X=np.array(X)
    self.mean=X.mean(axis=0)
    self.std=X.std(axis=0)

  def transform(self,X):
    X=np.array(X)
    X_scaled=(X-self.mean)/self.std
    return X_scaled

  def fit_transform(self,X):
    X=np.array(X)
    self.fit(X)
    return self.transform(X)

  def inverse_transform(self,X_scaled):
    X_scaled=np.array(X_scaled)
    X=X_scaled*self.std+self.mean
    return X

In [108]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [109]:
def forward (X,w,b):
    y_hat=np.dot(X,w)+b
    return y_hat

In [110]:
def mse(y,y_hat):
    loss=np.mean((y-y_hat)**2)
    return loss

In [111]:
def grad_w(X,y,y_hat):
    N=len(y)
    dW=(-2/N)*np.dot(X.T,(y-y_hat))
    return dW

def grad_b(y,y_hat):
    N=len(y)
    db=(-2/N)*np.sum(y-y_hat)
    return db

In [116]:
d=X_train.shape[1]
print(d)

3


In [151]:
w=np.random.randn(d,1)*0.02
w

array([[-0.01335401],
       [ 0.00936355],
       [-0.00022749]])

In [152]:
b=0

In [153]:
lr=0.01
epochs=1000

for epoch in range(epochs):
    y_hat=forward(X_train,w,b)

    loss=mse(y_train,y_hat)

    dw=grad_w(X_train,y_train,y_hat)
    db=grad_b(y_train,y_hat)

    w=w-lr*dw
    b=b-lr*db
    
    if epoch%100==0:
        print(f"epoch {epoch},loss= {loss}")

epoch 0,loss= 142.11449251226918
epoch 100,loss= 8.04891813648395
epoch 200,loss= 7.719081447433577
epoch 300,loss= 7.534484810206238
epoch 400,loss= 7.426844750562252
epoch 500,loss= 7.363840483984025
epoch 600,loss= 7.32672829992194
epoch 700,loss= 7.30463778433129
epoch 800,loss= 7.2912646167751385
epoch 900,loss= 7.2829525687705186


In [154]:
y_test_hat=np.dot(X_test, w) + b
test_mse=np.mean((y_test - y_test_hat)**2)
test_mae=np.mean(np.abs(y_test - y_test_hat))

print("Test MSE:",test_mse)
print("Test MAE:",test_mae)

Test MSE: 6.683436020950845
Test MAE: 1.9038399322336117


In [155]:
len(y_test_hat)

836

In [156]:
results=pd.DataFrame(X_test,columns=["Length","Diameter","Whole_weight"])
results["Actual_Age"]=y_test.flatten()
results["Predicted_Age"]=y_test_hat.flatten()
results.head(10)

Length  Diameter  Whole_weight  Actual_Age  Predicted_Age
0   0.275     0.195        0.0875         5.5       8.288323
1   0.585     0.460        0.7635        10.5      11.598889
2   0.595     0.455        0.8860        11.5      11.923272
3   0.400     0.295        0.2520         7.5       9.335920
4   0.670     0.540        1.4820        11.5      13.857362
5   0.600     0.475        1.1300        10.5      12.598671
6   0.595     0.465        1.1070        13.5      12.500661
7   0.595     0.475        1.0305        11.5      12.334615
8   0.450     0.335        0.3505         8.5       9.836674
9   0.620     0.510        1.2815        11.5      13.126838