In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('/content/glass.csv')

In [4]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [5]:
df.shape

(214, 10)

In [6]:
df.columns

Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object')

1. we need to predict the type of teh glass based on the features RI,Na,Mg,Al,Si,K,Ca,Ba,Fe.
2. all the features are numerical


In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [13]:
np.unique(df['Type'])

array([1, 2, 3, 5, 6, 7])

this shows that there are 6 types of glass which means its a multiclass classification .


In [14]:
df['y']=(df['Type']==1).astype(int)
print(np.unique(df['y']))

[0 1]


In [15]:
df=df.drop(columns=['Type'])

In [16]:
df.columns

Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'y'], dtype='object')

In [17]:
X=df.drop(columns=['y']).values
y=df['y'].values

In [20]:
X

array([[ 1.52101, 13.64   ,  4.49   , ...,  8.75   ,  0.     ,  0.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  7.83   ,  0.     ,  0.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  7.78   ,  0.     ,  0.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  8.44   ,  1.64   ,  0.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  8.48   ,  1.57   ,  0.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  8.62   ,  1.67   ,  0.     ]])

In [21]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [75]:
import random
def traintestsplit(X,y,testsize=0.3,randomseed=None):
  data=list(zip(X,y)) # this will pair the input to its particular output

  if randomseed:
    random.seed(randomseed)# this allows reusability and give the same split everytime
  random.shuffle(data) # it shuffles the data randomly in order to ensure better splitting

  # as we have shuffled the data we can find the idx (using the testsize) and it will act as the point of split in the dataset.
  idx=int(len(data)*(1-testsize))
  # all the rows in the range [0,idx] will belong to train set and rest will belong to test set
  train=data[:idx]
  test=data[idx:]

  #splitting it into X_train,X_test,y_train,y_test
  X_train,y_train=zip(*train)
  X_test,y_test=zip(*test)

  return np.array(X_train),np.array(X_test),np.array(y_train),np.array(y_test)

In [76]:
X_train,X_test,y_train,y_test=traintestsplit(X,y,0.2,42)

In [77]:
print(X_train[0])
print(X_test[0])

[ 1.51658 14.8      0.       1.99    73.11     0.       8.28     1.71
  0.     ]
[ 1.51569 13.24     3.49     1.47    73.25     0.38     8.03     0.
  0.     ]


# scaling the inputs
standard scaler-> z=(x-μ)/σ

In [78]:
class StandardScaler:
  def __init__(self):
    self.mean=None
    self.std=None

  def fit(self,X):
    X=np.array(X)
    self.mean=X.mean(axis=0)
    self.std=X.std(axis=0)

  def transform(self,X):
    X=np.array(X)
    X_scaled=(X-self.mean)/self.std
    return X_scaled

  def fit_transform(self,X):
    X=np.array(X)
    self.fit(X)
    return self.transform(X)

  def inverse_transform(self,X_scaled):
    X_scaled=np.array(X_scaled)
    X=X_scaled*self.std+self.mean
    return X

In [79]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [80]:
print(X_train[0])

[ 1.51658 14.8      0.       1.99    73.11     0.       8.28     1.71
  0.     ]


In [81]:
print(X_train_scaled[0])

[-0.60345604  1.79520791 -1.88856806  1.1043651   0.60776338 -0.72041984
 -0.49899921  3.30189801 -0.5905165 ]


In [82]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [83]:
def predict_prob(X,w,b):
  z=np.dot(X,w)+b
  p=sigmoid(z)
  return p

In [84]:
def loss(y,p):
  return -np.mean(y*np.log(p)+(1-y)*np.log(1-p))

In [85]:
def update_weights(X,y,w,b,lr):
  p=predict_prob(X, w, b)
  error=p-y
  dw=np.dot(X.T, error)/len(y)
  db=np.mean(error)
  w=w-lr*dw
  b=b-lr*db
  return w,b

In [86]:
w=np.zeros(X_train.shape[1])
b=0.0
lr=0.1
epochs=100

In [88]:
for i in range(epochs):
    w,b=update_weights(X_train_scaled,y_train,w,b,lr)
    print(f'epoch {i+1}: {loss(y_train,predict_prob(X_train_scaled,w,b))}')

epoch 1: 0.4881316698435818
epoch 2: 0.4877737560797
epoch 3: 0.4874211359310629
epoch 4: 0.48707368255079353
epoch 5: 0.4867312732200538
epoch 6: 0.4863937891838368
epoch 7: 0.4860611154943487
epoch 8: 0.4857331408615808
epoch 9: 0.48540975751069465
epoch 10: 0.4850908610458681
epoch 11: 0.48477635032026933
epoch 12: 0.4844661273118434
epoch 13: 0.48416009700462026
epoch 14: 0.4838581672752612
epoch 15: 0.4835602487845842
epoch 16: 0.48326625487381974
epoch 17: 0.4829761014653631
epoch 18: 0.48268970696780117
epoch 19: 0.48240699218500893
epoch 20: 0.48212788022911285
epoch 21: 0.48185229643713945
epoch 22: 0.48158016829116984
epoch 23: 0.48131142534183546
epoch 24: 0.48104599913499413
epoch 25: 0.48078382314143975
epoch 26: 0.4805248326895017
epoch 27: 0.4802689649004004
epoch 28: 0.4800161586262322
epoch 29: 0.47976635439046045
epoch 30: 0.4795194943308018
epoch 31: 0.4792755221443952
epoch 32: 0.47903438303515283
epoch 33: 0.478796023663193
epoch 34: 0.4785603920962643
epoch 35: 0.

In [89]:
def predict_label(p,thr=0.5):
  return (p>=thr).astype(int)

In [95]:
y_pred=predict_label(predict_prob(X_test_scaled,w,b),0.7)

In [96]:
np.mean(y_pred==y_test)

np.float64(0.6511627906976745)

In [100]:
y_pred=predict_label(predict_prob(X_test_scaled,w,b),0.8)
np.mean(y_pred==y_test)

np.float64(0.6046511627906976)